#!/usr/bin/env bash
# Bash script that manages manage_my_process
FILE=/tmp/my_process
PIDFILE=/var/run/my_process.pid

case "$1" in
    start)
        bash -c "while true; do echo 'I am alive!' >> $FILE; sleep 2; done" &
        echo $! > $PIDFILE
        echo "manage_my_process started"
        ;;
    stop)
        echo "manage_my_process stopped"
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            kill "$PID"
            rm -f $PIDFILE
	    rm -f $FILE
        fi
        ;;
    restart)    
	echo "manage_my_process restarted"
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            kill "$PID"
            rm -f $PIDFILE
        fi
        bash -c "while true; do echo 'I am alive!' >> $FILE; sleep 2; done" &
        echo $! > $PIDFILE
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
