#!/usr/bin/env bash
# Bash script that manages manage_my_process
PIDFILE=/tmp/my_process.pid
FILE=/alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process

do_start() {
	$FILE &
	echo $! > $PIDFILE
        echo "manage_my_process started"
}

do_stop() {
	echo "manage_my_process stopped"
	if [ -f $PIDFILE ]; then
		PID=$(cat $PIDFILE)
		kill "$PID"
		rm -f $PIDFILE
        fi
}
case "$1" in
    start)
	if [ ! -f $PIDFILE ]; then
		do_start
	fi
        ;;
    stop)
	    do_stop
        ;;
    restart)
	    echo "manage_my_process restarted"
	    if [ -f $PIDFILE ]; then
		    PID=$(cat $PIDFILE)
		    kill "$PID"
		    rm -f $PIDFILE
	    fi
	$FILE > /dev/null 2>&1 &
        echo $! > $PIDFILE
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
