#!/usr/bin/env bash
# Bash script that displays a story about the file /etc/passwd.
while IFS=: read -r username password userid groupid userinfo honedir shell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
