#!/usr/bin/env bash
# Bash script that display the visitor IP along with the HTTP status code from the Apache log file.
awk '{count[$1" "$9]++} END {for (combo in count) {split(combo, arr, " "); print count[combo], arr[1], arr[2]}}' apache-access.log | sort -k1,1nr | awk '{printf "%d %s %s\n", $1, $2, $3}'
