#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
end=1
while [ $end -le 10 ]
do
	if [ $end -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((end++))
done
