#!/usr/bin/env bash
# Bash script that displays Best School 10 times bad luck on 4 and good luck on 8.
end=1
while [ $end -le 10 ]
do
	if [ $end -eq 4 ]
	then
		echo "bad luck"
	elif [ $end -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((end++))
done
