#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
end=1
while [ $end -le 20 ]
do
	case $end in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $end
			;;
	esac
	((end++))
done
