#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts.new
sed -i '/localhost/d' /etc/hosts.new
sed -i '/facebook.com/d' /etc/hosts.new

echo '127.0.0.2 localhost' >> /etc/hosts.new
echo '8.8.8.8 facebook.com' >> /etc/hosts.new

cp -f /etc/hosts.new /etc/hosts

